#!/bin/sh
# =============================================================================
#  make-patch.sh -- regenerate 0001-r40250-linux-port.patch.
#
#  The patch in this directory is the entire Linux port.  It is the only thing
#  about the server source that this repository is allowed to contain: the
#  source it applies to belongs to Ymir/Webzen and is fetched at install time by
#  ../fetch-sources.sh.  So this script exists to make the patch reproducible --
#  anyone with the same two trees must get the same bytes out of it, or the
#  claim "the repository contains only our work" cannot be checked.
#
#  Usage:
#      ./make-patch.sh --pristine DIR --ported DIR [--out FILE]
#
#      --pristine  a directory that IS metin2/src/server, extracted fresh from
#                  the upstream metin2_server+src.tar.gz and never built in
#      --ported    a directory that IS the ported server/, i.e. the tree we
#                  actually compile (may contain build output; see PRUNE below)
#      --out       where to write (default: the patch next to this script)
#
#  Example, from a checkout and the reference archive:
#      mkdir -p /tmp/p && tar xzf metin2_server+src.tar.gz -C /tmp/p metin2/src/server
#      ./make-patch.sh --pristine /tmp/p/metin2/src/server --ported /opt/m2port/port40250/server
#
#  Determinism
#      * LC_ALL=C, so diff walks directories in one fixed order.
#      * The timestamps GNU diff puts after each --- / +++ filename are stripped.
#        They are the only part of a unified diff that depends on when it was
#        made, and patch(1) does not read them.
#      * The two trees are copied to fixed names a/ and b/ before diffing, so
#        the paths inside the patch never mention where they came from and
#        `patch -p1' works from the root of an extracted source tree.
#      * Everything a build leaves behind is pruned or excluded (PRUNE below),
#        so a ported tree that has been compiled in produces the same patch as
#        one that has not.
#
#  Run it twice and cmp the results; that check is built in at the end.
# =============================================================================
set -u
LC_ALL=C
export LC_ALL

HERE=$(cd "$(dirname "$0")" && pwd)
OUT="$HERE/0001-r40250-linux-port.patch"
PRISTINE=""
PORTED=""

die() { printf 'make-patch: %s\n' "$*" >&2; exit 2; }

while [ $# -gt 0 ]; do
    case "$1" in
        --pristine) PRISTINE="${2:-}"; shift 2 ;;
        --ported)   PORTED="${2:-}";   shift 2 ;;
        --out)      OUT="${2:-}";      shift 2 ;;
        -h|--help)  sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)          die "unknown argument: $1" ;;
    esac
done

[ -n "$PRISTINE" ] || die "--pristine is required"
[ -n "$PORTED" ]   || die "--ported is required"
[ -d "$PRISTINE/libthecore/src" ] || die "$PRISTINE does not look like metin2/src/server (no libthecore/src)"
[ -d "$PORTED/libthecore/src" ]   || die "$PORTED does not look like a server/ tree (no libthecore/src)"

TMP=$(mktemp -d) || die "could not make a temporary directory"
trap 'rm -rf "$TMP"' EXIT INT TERM

cp -a "$PRISTINE" "$TMP/a"
cp -a "$PORTED"   "$TMP/b"

# ---------------------------------------------------------------------------
#  PRUNE -- what must never enter the patch
# ---------------------------------------------------------------------------
# Two different reasons, and they are worth keeping apart.
#
#  (1) Build output.  Compiling in the ported tree leaves .o/.d files, OBJDIR/
#      and .obj/ directories, the linked `game' and `db' binaries and libsql's
#      generated Depend.linux.  None of it is source.  Depend.linux in
#      particular is regenerated by `make -C libsql dep', which the game image
#      runs before it compiles, so shipping it would only pin a stale one.
#
#  (2) Copies of upstream files.  common/service.h.crypton is a byte-for-byte
#      duplicate of upstream's common/service.h that somebody left behind while
#      experimenting; nothing includes it and nothing references the name.  It
#      is pruned deliberately and not merely incidentally: a new file in a patch
#      is emitted in full, so leaving it in would put twelve lines of Ymir's
#      header into this repository -- exactly the thing the whole arrangement
#      exists to avoid.  If you ever add a genuinely new source file, add it
#      here to the list of things you have thought about, not to the prune list.
#
# `=60' is an empty file created by a mistyped shell redirection. It is empty,
# so diff -N would ignore it anyway; it is removed so that nobody has to work
# that out.
rm -f  "$TMP/b/=60" \
       "$TMP/b/common/service.h.crypton" \
       "$TMP/b/libsql/Depend.linux" \
       "$TMP/b/db/db" \
       "$TMP/b/game/game"
rm -rf "$TMP/b"/*/src/OBJDIR "$TMP/b"/*/src/.obj \
       "$TMP/b"/*/OBJDIR     "$TMP/b"/*/.obj

# Excluded rather than pruned, because these names exist in BOTH trees -- the
# upstream tarball ships committed .o and .a files. Deleting them from b only
# would make the patch try to delete them from a.
EXCL="-x *.o -x *.a -x *.d -x Makefile.dep -x *.log -x tags"

# ---------------------------------------------------------------------------
#  Generate
# ---------------------------------------------------------------------------
gen() { # gen OUTFILE
    # shellcheck disable=SC2086
    ( cd "$TMP" && diff -ruN $EXCL a b ) \
        | sed -E 's/^(---|\+\+\+) ([^[:space:]]+)[[:space:]].*$/\1 \2/' \
        > "$1"
    # diff exits 1 when there are differences, which is the normal case here.
    return 0
}

gen "$TMP/body"
gen "$TMP/body2"
cmp -s "$TMP/body" "$TMP/body2" \
    || die "the diff is not reproducible -- generated twice, got different bytes"

FILES=$(grep -c '^diff ' "$TMP/body")
HUNKS=$(grep -c '^@@'    "$TMP/body")
ADDED=$(grep -c '^+[^+]' "$TMP/body")
REMOVED=$(grep -c '^-[^-]' "$TMP/body")

# ---------------------------------------------------------------------------
#  The port/feature boundary
# ---------------------------------------------------------------------------
# Everything in this patch used to be one thing: make 2014 FreeBSD code compile
# and run on Linux, changing no behaviour.  That is a claim a reviewer can check
# cheaply, and it is worth keeping checkable.  Anything that is NOT that -- a
# function the original server did not have -- must carry the marker
#
#     M2_FEATURE <name>
#
# on the line that introduces it.  This block finds those markers in the diff
# and names them in the header, so the next person to read the patch is told
# what is port and what is not before they read a single hunk, instead of having
# to work it out.  A patch with no markers gets the old, unqualified sentence.
FEATURES=$(grep '^+' "$TMP/body" \
           | sed -n 's/.*M2_FEATURE[[:space:]]\{1,\}\([A-Za-z0-9_-]\{1,\}\).*/\1/p' \
           | sort -u)

if [ -n "$FEATURES" ]; then
    FEATURE_SECTION="#  WHAT IS NOT PART OF THE PORT
#      A port changes no behaviour: the same source, running the same way, on a
#      different operating system.  These additions do change behaviour -- each
#      is a function the r40250 server never had -- so they are named here and
#      marked \`M2_FEATURE <name>' in the source they add:
#"
    for f in $FEATURES; do
        # Every file the marker appears in, in patch order.  awk rather than
        # grep -B, because a hunk can be further from its +++ line than any
        # fixed context window.
        WHERE=$( awk -v want="$f" '
            /^\+\+\+ / { file = $2; sub(/^b\//, "", file); next }
            /^\+/ && index($0, "M2_FEATURE") {
                line = $0
                sub(/.*M2_FEATURE[ \t]+/, "", line)
                sub(/[^A-Za-z0-9_-].*/, "", line)
                if (line == want && !(file in seen)) { seen[file] = 1; print "#              " file }
            }' "$TMP/body" )
        FEATURE_SECTION="$FEATURE_SECTION
#          $f
$WHERE"
    done
    FEATURE_SECTION="$FEATURE_SECTION
#
#      Nothing else in here adds a feature.  To check that claim:
#          grep -n 'M2_FEATURE' 0001-r40250-linux-port.patch
#      Every hit must be one of the names above.
#
"
else
    FEATURE_SECTION="#  WHAT IS NOT PART OF THE PORT
#      Nothing.  This patch is a pure port: it changes no behaviour, only what
#      the code needs to compile and run on Linux.  (No \`M2_FEATURE' marker was
#      found in the diff.)
#
"
fi

# The baseline this applies to, named by content rather than by where it sits.
# `find | sort | sha256sum' over the pristine tree is what anybody can re-run to
# check they are patching the same thing we diffed against.
BASE=$( cd "$PRISTINE" && find . -type f -print0 | LC_ALL=C sort -z \
        | xargs -0 sha256sum | sha256sum | awk '{print $1}' )
BASEN=$( find "$PRISTINE" -type f | wc -l | tr -d ' ' )

{
cat <<HEADER
# =============================================================================
#  0001-r40250-linux-port.patch
#
#  The Linux port of the Metin2 "r40250" server, as a patch and nothing else.
#
#  BASELINE
#      metin2/src/server, extracted from the upstream archive
#          metin2_server+src.tar.gz
#          sha256 6e9e7339935058f73fead81e609219b496adbc867dfeca70f633031730313001
#      which ../fetch-sources.sh downloads (or takes from a local copy of the
#      reference server files).  That tree is $BASEN files; the sha256 of its
#      sorted per-file checksum manifest is
#          $BASE
#
#  APPLY
#      cd <the extracted metin2/src/server>
#      patch -p1 --forward < 0001-r40250-linux-port.patch
#
#      It is generated with 3 lines of context and must apply with zero fuzz
#      and zero rejects.  If it does not, the source you extracted is not the
#      baseline above -- check the sha256, do not force the patch.
#
#  CONTENTS
#      $FILES files, $HUNKS hunks, +$ADDED / -$REMOVED lines.
#      Build output is not in here (no .o, .a, .d, Depend.linux, OBJDIR/, .obj/,
#      and neither of the linked game/db binaries), so a ported tree that has
#      been compiled in produces exactly these bytes too.
#
$FEATURE_SECTION#  MADE BY
#      ./make-patch.sh --pristine <fresh metin2/src/server> --ported <our server/>
#      Do not hand-edit this file.  Edit the ported tree and regenerate, or the
#      next person to check the port against upstream gets a wrong answer.
#
#  WHAT IT CHANGES, roughly
#      libthecore   kqueue -> epoll in fdwatch.c (the FreeBSD event loop had no
#                   Linux counterpart at all), signal and stdafx portability
#      game, db     FreeBSD-only headers and calls, the GetCommand() dangling
#                   stack pointer, FileMonitor, config, packet padding
#      Makefiles    a Linux branch in each one; the FreeBSD branch is left
#                   byte-identical so the same tree still builds on FreeBSD
#
#  LICENCE
#      These changes are ours and carry the repository's licence.  The source
#      they apply to is not ours and is not distributed here.
# =============================================================================
HEADER
cat "$TMP/body"
} > "$OUT"

printf 'wrote %s\n' "$OUT"
printf '  %s bytes, %s files, %s hunks, +%s/-%s lines\n' \
    "$(wc -c < "$OUT" | tr -d ' ')" "$FILES" "$HUNKS" "$ADDED" "$REMOVED"
printf '  baseline manifest sha256 %s (%s files)\n' "$BASE" "$BASEN"
